### ISSUE TITLE
bv aldoni la kartvelan skribsistemon

### ISSUE THREAD

**Issue by zmila** [salif/alfabetoj#1]
Estus agrable, se vi aldonus la kartvelan skribsistemon por la Esperanto (The Georgian script for Esperanto). 
Vidu: https://www.omniglot.com/conscripts/georgianesperanto.htm por la korespondaj literoj. 

ა | ბ | გ | დ | ე | ვ | ზ | თ | ი | ლ
A a | B b | G g | D d | E e | V v | Z z | T t | I i | L l

მ | ნ | ჲ | ო | ჟ | რ | ს | ჳ | უ | ფ
M m | N n | J j | O o | Ĵ ĵ | R r | S s | Ŭ ŭ | U u | P p

ქ | შ | ჩ | ც | ხ | ჯ | ჰ | ჶ |   
K k | Ŝ ŝ | Ĉ ĉ | C c | Ĥ ĥ | Ĝ ĝ | H h | F f |

**Comment by salif** [comment]
Done!

**Comment by salif** [comment]
I will delete this issue. The issue tracker is now on [Codeberg](https://codeberg.org/salif/alfabetoj/issues/1)
